const express = require('express')
const app = express()
const cors = require('cors')
const dotenv = require('dotenv')
const users = require("./routes/routes.js")
const usersProfile = require("./routes/profile.js")
dotenv.config()
require("./database/connect.js")
app.use(express.json())
app.use(cors())
app.use("/auth", users)
app.use("/", usersProfile)
app.listen(3000, ()=>console.log("server running"))